### PR TITLE
Updated logic to determine whether a point should be plotted on a chart

### PR DESCRIPTION
**Pull request by snrnats**
Updated logic of render points filtering. #244
Now it checks whether a point rectangle or its part is within a plot rectangle. Also I added logic to keep points that are needed to render empty values.

### CODE REVIEW

**Comment by APopatanasov** [comment]
@snrnats , thank you for your contribution. I will need some time to completely test the code in order to avoid missing some scenarios and setups that were missed with the previous fix. If everything is ok I will approve the request. 😄

**Comment by snrnats** [comment]
Sure. I worth to mention that there was one more affected scenario with previous code. It was possible to reproduce the issue with LineSeries
```
            <chart:RadCartesianChart.Resources>
                <DataTemplate x:Key="PointTemplate">
                    <Ellipse Width="1" Height="1" Stroke="Red" Fill="Black" />
                </DataTemplate>
            </chart:RadCartesianChart.Resources>
            <chart:RadCartesianChart.HorizontalAxis>
                <chart:DateTimeContinuousAxis LabelFormat="{}{0:d MMM}" MajorStepUnit="Day" MajorStep="1" />
            </chart:RadCartesianChart.HorizontalAxis>
            <chart:RadCartesianChart.VerticalAxis>
                <chart:LinearAxis HorizontalLocation="Right"/>
            </chart:RadCartesianChart.VerticalAxis>
```
Key points were that the point template should have width more than zero and vertical axis should be located at the right

**Comment by APopatanasov** [comment]
Hi @snrnats ,

Thank you for your patience. I was able to check the PR and tested a few scenarios and I am glad to inform you that everything looks fine. You can proceed and merge the PR after that I will move the logged issue to "Ready for Test" and it will further be tested. 

Thanks again for you collaboration. If you are interested on working on some of the other [issues ](https://github.com/telerik/UI-For-UWP/issues) and have some questions or concerns do not hesitate to ask. 😄

**Comment by snrnats** [comment]
Hi @APopatanasov ,

I have no other notes. Please merge the changes as I don't have access to do it.

**Comment by APopatanasov** [comment]
@snrnats The PR is merged. I will change the status of the issue to "Ready for test" and it will be tested further.

**Pull request merged**
