### PR TITLE
Add a check for Shift and CapsLock for azerty keyboard when 6 is pres…

### PR DESCRIPTION
**Pull request by APopatanasov**
…sed - when Shift or CapsLock are pressed 6 should not be treated as minus.

### CODE REVIEW

**Comment by Gimgur** [comment]
Hello,

Do you have an idea of the date this issue will be merge with master and available in a new nugget package?

thanks

**Comment by APopatanasov** [comment]
@Gimgur As we have recently released a new nuget package the next merge date is scheduled for May. However, you can still build nuget by yourself. For some more detailed information how to achieve this check the following wiki page:
https://github.com/telerik/UI-For-UWP/wiki/How-to-Build-UI-For-UWP-NuGet

Hope this helps.

**Comment by shanyrajagopalan** [comment]
Was there a release due today? I was told by Telerik that a release with the above fix will be available today.

**Comment by StefanNenchev** [comment]
@shanyrajagopalan I have provided a nuget package and binaries zip package in the ticket where we discussed the issue as the release is scheduled for the next Wednesday.

**Pull request merged**
