### PR TITLE
BugFixed: GridCellEditorModel.Container is not necessarily a Tuple.

### PR DESCRIPTION
**Pull request by kanryu**
For example, it is TextBlock.

This problem frequently occurs when the CancelEdit() method is called externally while editing RadDataGrid.

### CODE REVIEW

**Comment by APopatanasov** [comment]
Hi @kanryu ,

Thank you for you contribution. Could you please, send me a sample project that demonstrates the observed by you issue or your exact setup of the DataGrid.  You can log an [issue ](https://github.com/telerik/UI-For-UWP/issues)with all the required information. Without being able to observe the exact scenario I could not tell for sure if this is the right approach for fixing the issue.

Also, all the bug fixes, features are made against the development branch. Could you please, try to make the pull request against that branch? 

And finally in order to be able to approve your pull request you need also to sigh the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSfQAzVxnnfwRQmtJCVmB41_ig1gYow--Gr8qLvaDxJRNHPtUQ/viewform). Could you please sign it?

I am looking forward to hearing from you. 😄

**Comment by kanryu** [comment]
The place where the source code was changed is obvious from the pull request.
The procedure to reproduce it is as described above.

I think that confirmation of reproduction is exactly your job and it is inappropriate to ask that the issuer of pull requests seek it.
You should not impose your work on others.

I accepted the signatures you request, so this pull request could be merged into your source tree.

**Comment by APopatanasov** [comment]
@kanryu I will need some time to investigate the scenario in details and to confirm if the suggested fix is relevant.

I will write back to you once I have some more information to share.

**Comment by kanryu** [comment]
I added the sample application I used to confirm the operation. You will be able to confirm this problem.

However, building my fork as it is does not reproduce the problem. If I comment out changing the code of the pull request I originally posted, I can check the problem (the application ends improperly)

As I committed twice, the content of pull request seems to be changing, but please accept the first commit when you accept it.

**Comment by APopatanasov** [comment]
@kanryu Thank you for the provided project. Using it I was able to understand the complete scenario that crashes the DataGrid. I will need need some time to check how the scenario is affecting the DataGrid and confirm whether the added check is the right approach for fixing the issue.

Thank you for the understanding.

**Comment by APopatanasov** [comment]
@kanryu Thank you for your patience. I have checked the provided sample project and based on the scenario I could not accept the fix for the DataGridTyped column. 

Basically, when DataGrid enters in its edit mode for each column that has a CanUserEdit property set to true a container for editing is generated. For example for the Text column a TextBox editor is generated, for the Numeric column a RadNumericBox is generated and etc. When the CanUserEdit is changed from false to true in the provided scenario the method that generates container for the column is not invoked. Because of that container is not generated. So, when committing the edited row there is no container that can be disposed and the observed exception is thrown.

The excepted behavior for that scenario will be:

1. Row is edited.
2. CanUserEdit is changed from false to true.
3. A container is generated for the cell immediately after the property is changed.
4. If the value is changed from true to false the container should be disposed immediately after the property is changed.

Executing the above flow will prevent the control from throwing NullReferenceException. Feel free using the described above scenario to apply a fix  that will result in the desired behavior and I will be glad to review it again.

Thanks again for your patience.

**Comment by kanryu** [comment]
I have found a reproducing procedure where RadDataGrid is abusing and you should have understood it.
No matter what theory it is, this event is a fact, and it has to be modified as it is a bug.

My modification can surely prevent unauthorized termination. The fact that you do not accept my pull request means that you abandon the work you should do and that you have to locate and fix other solutions you can substitute for my request yourself .

**Comment by APopatanasov** [comment]
@kanryu 

Thank you for all your efforts and for reporting this case to us. We have discussed the particular scenario and indeed, the DataGrid getting into such invalid state could be considered problematic. At the same time, we do not believe that preventing the exception with null is the best approach here. Furthermore, the suggested null check could lead to other implications.

Let me elaborate again on why the grid becomes in invalid state - that is, because during an active edit operation, setting the CanUserEdit for the particular column causes the issue with the containers as discussed above.

I think that the proper way for this situation when CanUserEdit is being set to false during active edit operation, is to allow and require the developer to either cancel the current edit operation or to commit it. As we cannot know what the developer would prefer in his case, we cannot make this decision in the control. So, our proposal here would be to throw an exception, when one tries to set CanUserEdit to false/true, while the grid is in edit mode in the particular column. The exception will be with a descriptive message that mentions the requirement to cancel/comit before setting the property takes place. This way, the developer will be aware of the situation and will be able to take appropriate action.

**Comment by kanryu** [comment]
I think your recognition is clearly wrong. Because calling CancelEdit () while editing RadGridData will end incorrectly.

Controls that can not be expected to perform other operations during editing must be pointed out that there is a fatal defect. Such trouble should not be neglected.

**Comment by APopatanasov** [comment]
@kanryu I think you have misunderstood our proposal above - please have a look at it again. We basically say that the issue you see is happening because you set CanUserEdit while the grid is in edit mode. If you Cancel or Commit the edit operation prior to setting CanUserEdit, all will be fine.

**Comment by kanryu** [comment]
I think you are wrong. That's because it ends unexpectedly when calling CancelEdit () while editing RadDataGrid.

The exception occurred in DataGridTypedColumn.ClearEditorContainer (), because the cause fails to acquire the pair variable as well(pair become null).

Why is not only a DataGridTypedColumn null checked for other source code such as DataGridColumn class or DataGridTemplateColumn class being properly null checked? The quality standard of the source code contradicts.

You should not make your code mistake the responsibility of the application developer.

**Comment by kanryu** [comment]
The basis for sticking to the scenario is unknown.
The XAML application has a wider loose coupling between the widget and the application body than the Windows.Forms application, and there is little room to customize the widget.

I think that it is impossible to realize on the XAML tag the promise that you call "call CancelEdit() before changing CanUserEdit".
Therefore, your scenario is not feasible and there is little benefit to discuss.

**Comment by APopatanasov** [comment]
@kanryu The Cancel/CommitEdit operations are asynchronous. Because of that when the CanceEdit is called it gets invoked internally at a moment where the CanUserEdit is already changed - because of that the exception is observed. 

I have made [a small improvement ](https://github.com/telerik/UI-For-UWP/pull/290/commits/299da7ed3ad03ba77f999b37f8720c90131c9156)into your test project that demonstrates how the proposed in my previous responses approach is expected to work. Basically the changing of the CanUserEdit should be dispatcher and thus the CancelEdit will be completed before CanUserEdit is changed.

Please, check it.

**Comment by kanryu** [comment]
After testing the modifications of the application you showed, I was able to confirm that fixed. Thank you.

However, the CancelEdit method (Command) works asynchronously is not written in the manual, it is a complicated topic. It is counterintuitive to intuitive usage to require such measures. As we wrote above, null checks are done in other Column classes, so we should do it in this class as well. My opinion is still alive.

**Comment by APopatanasov** [comment]
@kanryu I am glad to here the suggested solution worked for you. 

I will close the current PR and will open an issue about the observed by you solution in the particular scenario. The right approach for fixing this issue we believe is to prevent changing the CanUserEdit while the row is editing and to thrown and exception that this is not a supported scenario.

If you are interested on working on this do not hesitate to make a PR with that particular fix.

**Pull request closed without merging**
