### PR TITLE
Error FormatValue and UpdateSourceTrigger=PropertyChanged

### PR DESCRIPTION
**Pull request by geotinc**
Error FormatValue and UpdateSourceTrigger=PropertyChanged when the ValueFormat is {0:0.##฿}
Works for dollars and euros.

### CODE REVIEW

**Comment by geotinc** [comment]
Hi,
It should be okay with my last commit.

**Comment by APopatanasov** [comment]
@geotinc  Indeed the observed behavior is caused by the CommitEdit method and more specifically by the TryParseValue method called inside it - the TryParse method could not parse the value with the applied format and because of that the value is cleaned.

I will need some time to check the new changes. For now everything seems to be working as expected. I will let you know if I find something. 😊

**Comment by APopatanasov** [comment]
@geotinc We have tried several scenarios and we were able to replicate the same behavior as the mentioned one in my initial review.

After further investigation of the issue we came to the conclusion that is caused by the CurrentCulture used by the control in its parsing. As the Culture you are currently using most probably has a CurrencySymbol different than the used one ("฿") the parsing could not be performed and because of that the mentioned issues are observed.

I totally agree with you initial [commit ](https://github.com/telerik/UI-For-UWP/pull/72/commits/da6b104a47e5002f8813a7930dc2c2ed38fe60a6) however, instead of adding the [logic ](https://github.com/telerik/UI-For-UWP/pull/72/commits/6be4c7259c94c3f38fb916af9cc1e905f8a43cdc)for the CommitEdit (that didn't fix all scenarios) I believe the best solution is to change the CurrencySymbol of the NumberFormat to be the desired one and thus the parsing should be working as expected:
`public sealed partial class MainPage : Page
{
    public MainPage()
    {
        **CultureInfo.CurrentCulture.NumberFormat.CurrencySymbol = "฿";**
        this.InitializeComponent();

        this.DataContext = new ViewModel();
            
    }
}`

If that is suitable for you could you please, revert the latest commit and I will merge your initial commit.

Hope the provided information about the parsing is helpful for you.

**Comment by APopatanasov** [comment]
Hi @geotinc ,
Could you please, let me know if the proposed above solution works for your scenario so, we could be able to proceed with this pull request?

**Comment by APopatanasov** [comment]
Hi @geotinc ,
As we haven't received any feedback from you I will merge your [initial commit ](https://github.com/telerik/UI-For-UWP/pull/72/commits/da6b104a47e5002f8813a7930dc2c2ed38fe60a6). I hope the provided above solution with the CurrencySymbol  worked for you.

**Pull request merged**
